'use client';
import {useEffect,useState} from 'react';
import {sourceUrl,testTypes,type CatalogRow} from './config';
export function Catalog({pt=false}:{pt?:boolean}){
 const t=(en:string,br:string)=>pt?br:en;
 const [rows,setRows]=useState<CatalogRow[]>([]),[error,setError]=useState(''),[search,setSearch]=useState(''),[language,setLanguage]=useState(''),[type,setType]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{const controller=new AbortController();fetch('/catalog.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>setRows(d.rows)).catch(e=>{if(e.name!=='AbortError')setError(pt?'Não foi possível carregar o catálogo. Recarregue a página.':'The catalog could not load. Reload the page.');});return()=>controller.abort();},[pt]);
 const languages=[...new Set(rows.map(r=>r.language))].sort();
 const filtered=rows.filter(r=>(!language||r.language===language)&&(!type||r.tests.includes(type))&&`${r.name} ${r.language} ${r.databases.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 const comparison=selected.map(id=>rows.find(r=>r.id===id)!).filter(Boolean);
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<3?[...s,id]:s);}
 return <div className="catalog-app"><div className="filter-bar"><div className="search-field"><label htmlFor="search">{t('Find a framework','Buscar framework')}</label><input id="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder={t('Search name, language or database…','Busque nome, linguagem ou banco…')}/></div><div><label htmlFor="language">{t('Language','Linguagem')}</label><select id="language" value={language} onChange={e=>{setLanguage(e.target.value);setPage(0);}}><option value="">{t('All languages','Todas as linguagens')}</option>{languages.map(l=><option key={l}>{l}</option>)}</select></div><div><label htmlFor="test-type">{t('Test coverage','Cobertura de testes')}</label><select id="test-type" value={type} onChange={e=>{setType(e.target.value);setPage(0);}}><option value="">{t('All test types','Todos os testes')}</option>{testTypes.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div><button className="reset-button" onClick={()=>{setSearch('');setLanguage('');setType('');setPage(0);}}>{t('Reset','Limpar')}</button></div>
 <div className="catalog-status"><span role="status">{rows.length?`${filtered.length} ${t('framework configurations','configurações de framework')}`:error||t('Loading source catalog…','Carregando catálogo…')}</span><span>{t('Select up to 3 to compare coverage','Selecione até 3 para comparar cobertura')} <strong>{selected.length}/3</strong></span></div>
 {comparison.length>0&&<div className="comparison"><div className="comparison-title"><strong>{t('Coverage comparison','Comparação de cobertura')}</strong><button onClick={()=>setSelected([])}>{t('Clear selection','Limpar seleção')}</button></div><div className="table-scroll" tabIndex={0} role="region" aria-label={t('Selected frameworks comparison','Comparação dos frameworks selecionados')}><table><caption className="sr-only">{t('Supported tests across selected framework configurations','Testes disponíveis nas configurações selecionadas')}</caption><thead><tr><th scope="col">{t('Test type','Tipo de teste')}</th>{comparison.map(r=><th scope="col" key={r.id}>{r.name}<small>{r.language} · {r.variants} {t('variants','variantes')}</small></th>)}</tr></thead><tbody>{testTypes.map(([id,name])=><tr key={id}><th scope="row">{name}</th>{comparison.map(r=><td key={r.id}><span className={r.tests.includes(id)?'supported':'unsupported'}>{r.tests.includes(id)?t('Available','Disponível'):t('Not configured','Não configurado')}</span></td>)}</tr>)}</tbody></table></div></div>}
 <div className="table-scroll" tabIndex={0} role="region" aria-label={t('Framework catalog','Catálogo de frameworks')}><table className="catalog-table"><caption className="sr-only">{t('Framework configurations from the source repository','Configurações de frameworks do repositório')}</caption><thead><tr><th scope="col">{t('Compare','Comparar')}</th><th scope="col">Framework</th><th scope="col">{t('Language','Linguagem')}</th><th scope="col">{t('Variants','Variantes')}</th><th scope="col">{t('Coverage','Cobertura')}</th><th scope="col">{t('Source','Código')}</th></tr></thead><tbody>{filtered.slice(page*15,page*15+15).map(r=><tr key={r.id}><td><label className="check-label"><input type="checkbox" checked={selected.includes(r.id)} disabled={selected.length===3&&!selected.includes(r.id)} onChange={()=>toggle(r.id)} aria-label={`${t('Compare','Comparar')} ${r.name}`}/></label></td><th scope="row"><a href={sourceUrl(r.path)}>{r.name}</a><small>{r.databases.filter(d=>d!=='None').join(' / ')||t('No database configured','Sem banco configurado')}</small></th><td><span className="language-tag">{r.language}</span></td><td className="numeric">{r.variants}</td><td><div className="coverage-dots" aria-label={r.tests.join(', ')}>{testTypes.map(([id,name])=><span key={id} className={r.tests.includes(id)?'test-enabled':'test-disabled'} title={`${name}: ${r.tests.includes(id)?t('available','disponível'):t('not configured','não configurado')}`}>{id==='cached-query'?'C':name[0]}</span>)}</div></td><td><a className="source-link" href={sourceUrl(r.path)} aria-label={`${t('View source for','Ver código de')} ${r.name}`}>↗</a></td></tr>)}</tbody></table></div>
 {rows.length>0&&filtered.length===0&&<div className="empty-catalog"><h3>{t('No frameworks match these filters.','Nenhum framework corresponde aos filtros.')}</h3><p>{t('Try another name or choose all languages.','Tente outro nome ou selecione todas as linguagens.')}</p></div>}
 <div className="pagination"><p>{t('Coverage combines variants; it is not a performance ranking.','A cobertura reúne variantes; não é um ranking de desempenho.')}</p><div><button disabled={page===0} onClick={()=>setPage(p=>p-1)} aria-label={t('Previous page','Página anterior')}>←</button><span>{page+1} / {Math.max(1,Math.ceil(filtered.length/15))}</span><button disabled={(page+1)*15>=filtered.length} onClick={()=>setPage(p=>p+1)} aria-label={t('Next page','Próxima página')}>→</button></div></div>
 </div>;
}
