import {repo} from './config';
export function Methodology({pt=false}:{pt?:boolean}){
 const t=(en:string,br:string)=>pt?br:en;
 const workloads=[
 ['json','JSON serialization','Serialização JSON','Return a freshly serialized object containing a message. This exercises routing, JSON encoding and HTTP response handling.','Retorne um objeto recém-serializado com uma mensagem. Exercita roteamento, codificação JSON e resposta HTTP.','{"message":"Hello, World!"}','application/json'],
 ['db','Single query','Consulta simples','Fetch one random World row by ID and serialize its id and randomNumber as JSON. Access the database for each request using the declared connectivity approach.','Busque uma linha aleatória de World por ID e serialize id e randomNumber em JSON. Acesse o banco em cada requisição usando a abordagem declarada.','{"id":123,"randomNumber":456}','application/json'],
 ['query','Multiple queries','Múltiplas consultas','Read the requested number of random World rows individually and return a JSON array. The queries parameter is constrained to 1–500. Published charts normally highlight 20 queries per request.','Leia individualmente a quantidade solicitada de linhas aleatórias de World e retorne um array JSON. O parâmetro queries é limitado a 1–500. Os gráficos publicados normalmente destacam 20 consultas por requisição.','[{"id":123,"randomNumber":456}, …]','application/json'],
 ['cached-query','Cached queries','Consultas em cache','Fetch random World records from an application-side cache and return an array. This is a separate workload from database reads; see the full rules for cache population and correctness.','Busque registros aleatórios de World no cache da aplicação e retorne um array. É uma carga separada das leituras no banco; confira as regras completas de preenchimento do cache e correção.','[{"id":123,"randomNumber":456}, …]','application/json'],
 ['fortune','Fortunes','Fortunes','Read all fortune messages, add a new message at request time, sort by message text and render a server-side HTML template. Escape untrusted HTML and preserve UTF-8.','Leia todas as mensagens, adicione uma mensagem durante a requisição, ordene pelo texto e renderize um template HTML no servidor. Escape HTML não confiável e preserve UTF-8.','<table>\n  <tr><th>id</th><th>message</th></tr>\n  …\n</table>','text/html; charset=UTF-8'],
 ['update','Data updates','Atualizações de dados','Read random World rows, change their randomNumber values, persist the updates and return the modified rows as JSON. Query count controls how many rows are updated.','Leia linhas aleatórias de World, altere randomNumber, persista as atualizações e retorne as linhas modificadas em JSON. A quantidade de consultas controla quantas linhas são atualizadas.','[{"id":123,"randomNumber":789}, …]','application/json'],
 ['plaintext','Plaintext','Texto simples','Return the fixed text response. HTTP pipelining and larger load levels exercise the HTTP stack with minimal application work.','Retorne a resposta de texto fixa. Pipelining HTTP e níveis maiores de carga exercitam a stack HTTP com trabalho mínimo da aplicação.','Hello, World!','text/plain']];
 return <div className="methodology-page"><div className="methodology-intro"><p>{t('These workloads isolate different parts of a web application. Select equivalent implementations and inspect their source before treating a ranking as a production prediction.','Essas cargas isolam partes diferentes de uma aplicação web. Selecione implementações equivalentes e inspecione o código antes de usar um ranking como previsão para produção.')}</p><a href={pt?'/pt/guide/#procedure':'/guide/#procedure'}>{t('How measurements are collected','Como as medições são coletadas')} ↗</a></div><div className="methodology-list">{workloads.map(([id,en,br,description,descriptionBr,response,type],i)=><article id={id} key={id}><div className="workload-number">{String(i+1).padStart(2,'0')}</div><div className="workload-copy"><span className="eyebrow">{id}</span><h2>{t(en,br)}</h2><p>{t(description,descriptionBr)}</p><a className="text-link" href={`${repo}/tree/master/toolset/test_types/${id}`}>{t('Inspect the verifier','Inspecione o verificador')} ↗</a></div><div className="response-example"><div><span>{t('RESPONSE SHAPE','FORMATO DA RESPOSTA')}</span><code>{type}</code></div><pre><code>{response}</code></pre><small>{t('Illustrative response structure; not a measured result.','Estrutura ilustrativa da resposta; não é um resultado medido.')}</small></div></article>)}</div><div className="methodology-links"><a className="button primary" href="https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview">{t('Full source & requirements','Requisitos e código completos')} ↗</a><a className="text-link" href={pt?'/pt/guide/#faq':'/guide/#faq'}>{t('Interpretation & questions','Interpretação e perguntas')} ↗</a></div></div>;
}
