'use client';
import {selectedSample,milliseconds,baselineFor,type Entry,type Snapshot} from './official-model';
const colors=['var(--series-one)','#51c7f4','#bd9aef'];
export function PerformanceChart({snapshot,kind,selection,view,entries,selected,pt=false}:{snapshot:Snapshot;kind:string;selection:string;view:string;entries:Entry[];selected:Entry[];pt?:boolean}){
 const t=(en:string,br:string)=>pt?br:en;
 const number=(value:number)=>value.toLocaleString(pt?'pt-BR':'en-US',{maximumFractionDigits:2});
 if(view==='table'||view==='bars')return null;
 if(view==='curve'){
 const plotted=(selected.length?selected:entries.filter(e=>selectedSample(e,'best')).slice(0,3)).filter(e=>!e.failed),levels=snapshot.levels[kind]??[];
 const maximum=Math.max(1,...plotted.flatMap(entry=>entry.samples.map(s=>s?.rps??0))),x=(i:number)=>70+i*610/Math.max(1,levels.length-1),y=(value:number)=>235-value/maximum*180;
 const compact=(value:number)=>new Intl.NumberFormat(pt?'pt-BR':'en-US',{notation:'compact',maximumFractionDigits:1}).format(value);
 return <div className="visual-panel curve-panel"><div className="visual-heading"><div><span className="eyebrow">{t('LOAD PROFILE','PERFIL DE CARGA')}</span><h4>{t('Throughput across load levels','Vazão entre níveis de carga')}</h4></div><span>{t('requests / second','requisições / segundo')}</span></div><p>{t('Select up to three implementations in the table to plot them. Load levels are spaced as categories; missing samples leave gaps.','Selecione até três implementações na tabela para desenhar suas curvas. Níveis de carga são categorias; amostras ausentes deixam lacunas.')}</p><div className="curve-scroll"><svg viewBox="0 0 740 290" role="img" aria-label={t('Throughput by load level; exact values in the all samples table','Vazão por nível de carga; valores exatos na tabela de todas as amostras')}><title>{t('Throughput by load level','Vazão por nível de carga')}</title>{[0,.25,.5,.75,1].map(ratio=><g key={ratio}><line x1="70" x2="680" y1={y(maximum*ratio)} y2={y(maximum*ratio)} className="chart-grid"/><text x="57" y={y(maximum*ratio)+4} textAnchor="end">{compact(maximum*ratio)}</text></g>)}{levels.map((level,i)=><text key={i} x={x(i)} y="263" textAnchor="middle">{level.toLocaleString(pt?'pt-BR':'en-US')}</text>)}{plotted.map((entry,idx)=>{const segments:string[][]=[[]];entry.samples.slice(0,levels.length).forEach((sample,i)=>{if(sample)segments[segments.length-1].push(`${x(i)},${y(sample.rps)}`);else segments.push([]);});return <g key={entry.id}>{segments.filter(s=>s.length>1).map((points,i)=><polyline key={i} points={points.join(' ')} fill="none" stroke={colors[idx]} strokeWidth="2.5"/>)}{entry.samples.slice(0,levels.length).map((sample,i)=>sample&&<circle key={i} cx={x(i)} cy={y(sample.rps)} r="4" fill={colors[idx]}><title>{entry.display} · {levels[i]}: {number(sample.rps)} req/s</title></circle>)}</g>;})}<text x="375" y="288" textAnchor="middle">{['query','update','cached-query'].includes(kind)?t('queries per request','consultas por requisição'):t('concurrent clients','clientes simultâneos')}</text></svg></div><div className="chart-legend">{plotted.map((entry,i)=><span key={entry.id}><i style={{background:colors[i]}}/>{entry.display}</span>)}</div>{!plotted.length&&<p>{t('No valid measurements to plot.','Sem medições válidas para desenhar.')}</p>}</div>;
 }
 const data=entries.map(entry=>{const sample=selectedSample(entry,selection);let value=sample?.rps??null;if(view==='latency')value=sample?milliseconds(sample.latency):null;if(view==='overhead'){const baseline=baselineFor(entry,snapshot.tests[kind]??[],selection);value=sample&&baseline?.sample?.rps?sample.rps/baseline.sample.rps*100:null;}return {entry,value};}).filter((row):row is {entry:Entry;value:number}=>row.value!==null&&Number.isFinite(row.value)).slice(0,8);
 const max=Math.max(1,...data.map(row=>row.value));
 const heading=view==='latency'?t('Lowest average latency','Menor latência média'):view==='overhead'?t('Throughput relative to platform','Vazão relativa à plataforma'):t('Leading implementations','Implementações em destaque');
 return <div className="visual-panel"><div className="visual-heading"><div><span className="eyebrow">{t('MEASURED PERFORMANCE','DESEMPENHO MEDIDO')}</span><h4>{heading}</h4></div><span>{view==='latency'?t('lower is better · ms','menor é melhor · ms'):view==='overhead'?t('% of baseline RPS','% do RPS da base'):t('higher is better · req/s','maior é melhor · req/s')}</span></div><div className="rank-bars">{data.map(({entry,value},i)=><div className="rank-bar" key={entry.id}><span className="rank-bar-name"><small>{String(i+1).padStart(2,'0')}</small><strong title={entry.display}>{entry.display}</strong><i>{String(entry.meta.language??'')}</i></span><span className="rank-bar-track" aria-hidden="true"><i style={{width:`${value/max*100}%`,background:view==='latency'?'var(--series-two)':'var(--series-one)'}}/></span><span className="rank-bar-value">{number(value)}{view==='overhead'?'%':''}</span></div>)}</div>{!data.length&&<p>{t('No valid measurements or declared baselines for this view.','Sem medições válidas ou bases declaradas para esta visualização.')}</p>}<p className="chart-footnote">{t('Up to 8 entries from the current filters. The complete result table is below.','Até 8 entradas dos filtros atuais. A tabela completa de resultados está abaixo.')}</p></div>;
}
