import {repo} from './config';
import {ThemeToggle} from './theme';
const paths={results:'/',frameworks:'/frameworks/',runs:'/runs/',methodology:'/methodology/',guide:'/guide/'};
export type Section=keyof typeof paths;
export function WorkspaceShell({pt=false,active='results',children}:{pt?:boolean;active?:Section;children:React.ReactNode}){
 const t=(en:string,br:string)=>pt?br:en,prefix=pt?'/pt':'';
 const links:[Section,string][]=[['results',t('Results','Resultados')],['frameworks',t('Frameworks','Frameworks')],['runs',t('Your runs','Suas medições')],['methodology',t('Methodology','Metodologia')],['guide',t('Project guide','Guia do projeto')]];
 return <><a className="skip" href="#main">{t('Skip to content','Ir para o conteúdo')}</a><div className="betterweb-site"><header className="bw-header"><div className="bw-container bw-header-inner"><a className="bw-brand" href="https://better-web.org"><svg width="27" height="27" viewBox="0 0 28 28" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m9 7-6 7 6 7m10-14 6 7-6 7m-3-17-4 20"/></svg><strong>BetterWeb</strong><span>benchmarks</span></a><nav aria-label={t('Main navigation','Navegação principal')}>{links.map(([id,label])=><a key={id} href={`${prefix}${paths[id]}`} aria-current={active===id?'page':undefined}>{label}</a>)}</nav><div className="bw-header-actions"><ThemeToggle pt={pt}/><a className="bw-language" href={`${pt?'':'/pt'}${paths[active]}`} lang={pt?'en':'pt-BR'}>{pt?'EN':'PT'}</a><a className="bw-source" href={repo}>GitHub <span aria-hidden="true">↗</span></a></div></div></header><div className="bw-container bw-content">{children}</div><footer className="bw-footer"><div className="bw-container"><div className="bw-footer-top"><div><a className="bw-brand" href="https://better-web.org"><strong>BetterWeb</strong><span>benchmarks</span></a><p>{t('Explore the performance behind the web.','Explore o desempenho por trás da web.')}</p></div><div><span>{t('PROJECT','PROJETO')}</span><a href={repo}>{t('Source code','Código-fonte')} ↗</a><a href="https://www.techempower.com/benchmarks/">TechEmpower ↗</a><a href="https://tfb-status.techempower.com/">{t('Continuous results','Resultados contínuos')} ↗</a></div><div><span>{t('EXPLORE','EXPLORE')}</span><a href={`${prefix}/guide/#history`}>{t('Previous rounds','Rodadas anteriores')}</a><a href={`${prefix}/guide/#environment`}>{t('Environment','Ambiente')}</a><a href={`${prefix}/guide/#faq`}>FAQ</a></div><div><span>BETTER WEB</span><a href="https://better-web.org">{t('The ecosystem','O ecossistema')} ↗</a><a href="https://perfratio.better-web.org">perfratio ↗</a><a href="https://github.com/betterwebinit">GitHub ↗</a></div></div><div className="bw-footer-bottom"><p>{t('Independent Better Web portal. Published data by TechEmpower. Original BSD-3-Clause attribution preserved.','Portal independente da Better Web. Dados publicados pela TechEmpower. Atribuição BSD-3-Clause original preservada.')}</p><a href="https://www.techempower.com/benchmarks/">{t('Original benchmark site','Site original dos benchmarks')} ↗</a></div></div></footer></div></>;
}
